server:
  port: 8086

feign:
  client:
    config:
      default:                # по умолчанию для всех Feign клиентов
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic
      transfer-service:
        url: http://localhost:8085
        loggerLevel: full  # полное логирование для отладки

spring:
  application:
    name: payment-orchestrator-service

  scheduler:
    outbox:
      interval: 5000 # миллисекунд

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: payment-orchestrator-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.bankx.paymentorchestrator.*"
        spring.json.type.mapping: kafkaEvent:com.bankx.paymentorchestrator.dto.KafkaEvent
        # Настройки надежности
        isolation.level: read_committed
        max.poll.records: 10  # Обработка небольшими батчами для идемпотентности
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1
        compression.type: snappy  # алгоритм сжатия сообщения
        linger.ms: 10  # ожидание, чтобы собрать больше сообщений в один батч
        batch.size: 16384
    listener:
      type: batch
      ack-mode: manual_immediate

# Кастомные настройки Kafka топиков - дописать
kafka:
  topics:
    send-outbox-event: transfer.command    # topic for send command to transfer service
    transfer-status: transfer.status       # topic for transfer status


# Micrometer метрики для Kafka, Resilience4j для retry и circuit breaker, management (Actuator) - добавить также в помник

# Логирование
logging:
  level:
    com.bankx.paymentorchestrator: DEBUG
    org.springframework.kafka: DEBUG
    org.apache.kafka: WARN
  # написать паттерн шаблона строки лога, когда будут метрики и трассировка
